### ISSUE TITLE
There is a bug in Line No 7 of Hemandra Code 

### ISSUE THREAD

**Issue by bipeensinha** [bipeensinha/Netlinkdemo#1]
Hi Team,

I just discover there is bug in code at Line 7. It is going impact the Final Build . Pease get it corrected .
![a](https://user-images.githubusercontent.com/49720823/107312851-61f5f300-6ab7-11eb-9782-f6987e22bef1.png)

**Comment by manishraghuvanshi1985** [comment]
HI i recieved this bug. And working on it.

**Comment by abhishek-learnings** [comment]
I am working on it.

**Comment by AnuragJain999** [comment]
Hemendra what you have done; fix it.

**Comment by hdhakaita** [comment]
Test Comments1

**Comment by bipeensinha** [comment]
Thanks Manish and Abhishek

**Comment by Samir3107** [comment]
Yes I can see it

**Comment by bipeensinha** [comment]
Thank You , Issues has been Resolved 
![thank](https://user-images.githubusercontent.com/49720823/107313132-ecd6ed80-6ab7-11eb-8cd7-bb89ed068297.jpg)
